stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  WITH_PRECICE: "NO"
  CMAKE_BUILD_TYPE: "Release"
  TOL: "1e-8"

#before_script:
#  - sudo apt-get update
#  - sudo apt install -y cmake gcc g++ gfortran libtool autoconf automake
#  - sudo apt-get install -y libcgns-dev libhdf5-dev libopenblas0 
before_script:
  - pip install h5py 
  - pip install pytest
  - pip install pyprecice
  - export PATH=$PATH:/usr/local/mbdyn/bin

build_dust_alone:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - mkdir build && cd build 
    - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DWITH_PRECICE=$WITH_PRECICE ../
    - make -j8
    - echo "Build $CMAKE_BUILD_TYPE, USE_PRECICE =$WITH_PRECICE completed"
    - cd ..
  artifacts:
    paths:
      - build/bin/ 
    untracked: true
    
#test_single_components:   # This job runs in the test stage.
#  stage: test    # It only starts when the job in the build stage completes successfully.
#  script:
#    - python tests/single/static/run_mir_static_ll.py -t $TOL
#    - python tests/single/static/run_mir_static_v.py -t $TOL
#    - python tests/single/static/run_mir_static_p.py -t $TOL
#  needs: 
#    - "build-job"

test_mirror_static_components: 
  stage: test
  script: 
    - python tests/mir_test/static/run_mir_static_ll.py -t $TOL
    - python tests/mir_test/static/run_mir_static_v.py -t $TOL
    - python tests/mir_test/static/run_mir_static_p.py -t $TOL
  needs:
    - "build_dust_alone"

test_mirror_dynamic_components: 
  stage: test
  script: 
    - python tests/mir_test/dynamic/run_mir_dynamic_ll.py -t $TOL
    - python tests/mir_test/dynamic/run_mir_dynamic_v.py -t $TOL
    - python tests/mir_test/dynamic/run_mir_dynamic_p.py -t $TOL
  needs:
    - "build_dust_alone"
    - "test_mirror_static_components" 

test_symmetry_static_components: 
  stage: test
  script:
    - python tests/sym_test/static/run_sym_static_ll.py -t $TOL
    - python tests/sym_test/static/run_sym_static_v.py -t $TOL
    - python tests/sym_test/static/run_sym_static_p.py -t $TOL
  needs:
    - "build_dust_alone"

test_symmetry_dynamic_components: 
  stage: test
  script: 
    - python tests/sym_test/dynamic/run_sym_dynamic_ll.py -t $TOL
    - python tests/sym_test/dynamic/run_sym_dynamic_v.py -t $TOL
    - python tests/sym_test/dynamic/run_sym_dynamic_p.py -t $TOL
  needs:
    - "build_dust_alone"
    - "test_symmetry_static_components"

build_dust_coupled: 
  stage: test
  script: 
    - rm -rf build
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DWITH_PRECICE=YES ../
    - make -j8
    - echo "Build $CMAKE_BUILD_TYPE, USE_PRECICE=YES completed"
    - cd ..
  artifacts:
    paths:
      - build/bin/ 
    untracked: true
  needs: 
    - "build_dust_alone"
    - "test_symmetry_static_components"

test_mirror_coupled_components: 
  stage: test
  script:  
    - python tests/mir_test/coupled/run_mir_coupled_v.py -t $TOL
    - python tests/mir_test/coupled/run_mir_coupled_p.py -t $TOL
    - python tests/mir_test/coupled/run_mir_coupled_ll.py -t $TOL
  needs: 
    - "build_dust_coupled" 
    - "test_mirror_static_components"

test_symmetry_coupled_components:
  stage: test
  script:  
    - python tests/sym_test/coupled/run_sym_coupled_v.py -t $TOL
    - python tests/sym_test/coupled/run_sym_coupled_p.py -t $TOL
    - python tests/sym_test/coupled/run_sym_coupled_ll.py -t $TOL
  needs: 
    - "build_dust_coupled" 
    - "test_symmetry_static_components"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."